
package Interfaces;

import DATOS.ClsVendedores;
import DOMINIOS.ClsEmpleados;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIOTC
 */
public class InterfazComision extends javax.swing.JFrame {
    
    ClsVendedores empleadosJDBC=new ClsVendedores();
    DefaultTableModel dtm1 = new DefaultTableModel(); 

    
    public InterfazComision() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("InterfazComision");
        
//cambio de la tabla
        String [] titulo=new String[]{"codigo:","nombre","enero","febrero","marzo","total","promedio"};
        dtm1.setColumnIdentifiers(titulo);
        jTable1.setModel(dtm1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelEnero = new javax.swing.JLabel();
        jLabelFebrero = new javax.swing.JLabel();
        jLabelMarzo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        TXT = new javax.swing.JTextField();
        TXT1 = new javax.swing.JTextField();
        TXT2 = new javax.swing.JTextField();
        TXT3 = new javax.swing.JTextField();
        TXT4 = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButtonInf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Btneliminar = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel1.setText("Made by Jaime Caleb Molina Moran");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        titulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titulo.setText("RESULTADO DE COMISIONES");

        jLabelNombre.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelEnero.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabelEnero.setText("Enero:");

        jLabelFebrero.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabelFebrero.setText("Febrero:");

        jLabelMarzo.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabelMarzo.setText("Marzo:");

        jLabelId.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabelId.setText("ID:");

        TXT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTActionPerformed(evt);
            }
        });

        TXT1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TXT2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT2ActionPerformed(evt);
            }
        });

        TXT3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT3ActionPerformed(evt);
            }
        });

        TXT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT4ActionPerformed(evt);
            }
        });

        jButtonInsert.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonInsert.setText("Insertar");
        jButtonInsert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonInf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonInf.setText("Mostrar Info ");
        jButtonInf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfActionPerformed(evt);
            }
        });

        jTable1.setBackground(javax.swing.UIManager.getDefaults().getColor("Viewport.background"));
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Enero", "Febrero", "Marzo ", "Total", "Promedio"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 0, 0));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        Btneliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Btneliminar.setText("Eliminar");
        Btneliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtneliminarActionPerformed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonUpdate.setText("Actualizar");
        jButtonUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEnero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelFebrero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMarzo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(180, Short.MAX_VALUE)
                                .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButtonInf)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(Btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT1)
                    .addComponent(jLabelEnero)
                    .addComponent(jLabelFebrero)
                    .addComponent(TXT2)
                    .addComponent(jLabelMarzo)
                    .addComponent(TXT3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId)
                    .addComponent(TXT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT4ActionPerformed

    private void TXT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT3ActionPerformed

    private void TXT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT2ActionPerformed

    private void TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        ClsEmpleados update = new ClsEmpleados();

        update.setCodigo(Integer.parseInt(TXT4.getText()));
        update.setNombre(TXT.getText());
        update.setEnero(Integer.parseInt(TXT1.getText()));
        update.setFebrero(Integer.parseInt(TXT2.getText()));
        update.setMarzo(Integer.parseInt(TXT3.getText()));

        empleadosJDBC.Update(update);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void BtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtneliminarActionPerformed

        ClsEmpleados delete = new ClsEmpleados();
        delete.setCodigo(Integer.parseInt(TXT4.getText()));

        empleadosJDBC.deleteData(delete);
    }//GEN-LAST:event_BtneliminarActionPerformed

    private void jButtonInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfActionPerformed

        ClsVendedores all = new ClsVendedores();
        DefaultTableModel table = all.showInf();

        jTable1.setModel(table);
    }//GEN-LAST:event_jButtonInfActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed

        ClsEmpleados insert = new ClsEmpleados();

        insert.setNombre(TXT.getText());
        insert.setEnero(Integer.parseInt(TXT1.getText()));
        insert.setFebrero(Integer.parseInt(TXT2.getText()));
        insert.setMarzo(Integer.parseInt(TXT3.getText()));

        empleadosJDBC.insert(insert);
    }//GEN-LAST:event_jButtonInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazComision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazComision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazComision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazComision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazComision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btneliminar;
    private javax.swing.JTextField TXT;
    private javax.swing.JTextField TXT1;
    private javax.swing.JTextField TXT2;
    private javax.swing.JTextField TXT3;
    private javax.swing.JTextField TXT4;
    private javax.swing.JButton jButtonInf;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEnero;
    private javax.swing.JLabel jLabelFebrero;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMarzo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
